name: Build ICS PNG
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python scripts/ics2png.py
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/ics.png
          git commit -m "Update ics.png" || exit 0
          git push
